### ISSUE TITLE
Erreur d'affichage - v12

### ISSUE THREAD

**Issue by jbhemmer** [xperseguers/theodia#1]
Hello,

J'ai chargé les calendriers sur une page et apparemment, ça saute: 

<img width="1352" alt="TYPO3_Exception" src="https://github.com/xperseguers/theodia/assets/5025581/68653cb4-fdf8-40a0-a3d8-d80bbcbbbdfc">

JBH

**Comment by xperseguers** [comment]
OK, peux-tu stp m'indiquer quel calendrier fait ça ? Parce que c'est marrant mais avec l'UP de Marly j'ai toujours eu une date de fin...

**Comment by jbhemmer** [comment]
C'est assez bizarre. C'est quand je charge x lieux dans le plugin que ça fait planter.

<img width="814" alt="Modifier_Contenu_de_la_page___Sans_titre___sur_la_page__Chapelle_des_Marches__Broc__·_Unité_pastorale_Notre-Dame_de_l’Evi__TYPO3_CMS_12_4_7_" src="https://github.com/xperseguers/theodia/assets/5025581/49047826-1e9b-4211-b5bb-8a37e0af3149">

**Comment by xperseguers** [comment]
OK, mais donne-moi stp la config (du site) qui va avec, je ne peux pas deviner les UIDs avec juste les noms :)

**Comment by jbhemmer** [comment]
Top merci :-)
