### ISSUE TITLE
Plugin "theodia - Lieu" - plante

### ISSUE THREAD

**Issue by jbhemmer** [xperseguers/theodia#2]
Hello,

Lorsque j'active le plugin theodia - Lieu et que je cherche à afficher "Notre Dame des Marches", voici l'erreur:

<img width="1297" alt="TYPO3_Exception" src="https://github.com/xperseguers/theodia/assets/5025581/b1f7e4fe-7a95-4eb9-b64a-5afd3120a73b">

JBH

**Comment by xperseguers** [comment]
Hello, il faut absolument que tu me donnes systématiquement le ou les calendriers que tu configures pour ton site (ID theodia) et/ou l'ID du lieu dans ce cas (je peux me débrouiller pour le récupérer même sans calendrier). Parce que tu connais cette info mais moi ça me fait perdre du temps de devoir chercher dans theodia l'ID de "Notre Dame des Marches"...

Merci :)

**Comment by jbhemmer** [comment]
C'est le calendrier 477. Si je ne te l'ai pas donné, c'est que ça saute pour n'importe quel lieu

**Comment by jbhemmer** [comment]
Je pensais que l'erreur ci-dessus pouvait te permettre de "comprendre".

**Comment by xperseguers** [comment]
Non, parce qu'en fait l'erreur se produit (produisait) que s'il n'y a pas de photos associées :)

**Comment by xperseguers** [comment]
Ce plugin est utilisé depuis 3 ans sans problème sur l'UP Sainte-Claire, donc si ça plante c'est que quelque chose est différent de l'environnement "idéal" que j'ai avec paroisse.ch. D'où vraiment le besoin de toujours bien expliquer comment reproduire. Merci !
