### ISSUE TITLE
Plugin - Récupérer les dispositions (Layout) en FE

### ISSUE THREAD

**Issue by jbhemmer** [xperseguers/theodia#4]
Merci de récupérer les dispositions (Layout) en FE.

JBH

**Comment by xperseguers** [comment]
Pour une prochaine fois, merci d'être un peu plus précis dans la demande, pour le cas où on discute par téléphone mais que je ne peux pas forcément traiter de suite.

## Contexte

- Nous mettons plusieurs fois le même plugin sur une page, pour afficher différentes informations d'un lieu de culte
- Nous souhaitons travailler avec les différents "layouts" pour choisir ce qui doit être affiché

## Problématique

- L'information du layout choisi n'est pas disponible dans le template Fluid

## Solution

- Passer les informations de configuration du plugin au template Fluid
