### ISSUE TITLE
Add button Show more events if we dont use Iframe

### ISSUE THREAD

**Issue by Hasan-Shaker** [xperseguers/theodia#6]
Hello,
We need do same thing that's in the frame.
Like #5

**Comment by xperseguers** [comment]
Right now unsure how to best implement that and if that should be part of the base extension. I use it like that for quite some years on www.paroisse.ch and I absolutely do not want people to be able to load "more" events.

That may possibly be a plugin option (default to `false`) but that means AJAX request to implement and many things that may pollute the extension. As such, to be investigated, prototyped, and possibly still be part of your "site" extension if you need it and not for sure become part of the extension.

**Comment by xperseguers** [comment]
@Hasan-Shaker After discussing with JB, please have a look at this feature branch https://github.com/xperseguers/theodia/tree/feature/6-more-button, test and report if everything is fine for you.

I'll then merge that branch onto the main branch.

**Comment by Hasan-Shaker** [comment]
Hello,
I agree with you ( that means AJAX request to implement and many things that may pollute the extension ), I'm thinking and search about how best to do this with as little pollution as possible.

**Comment by xperseguers** [comment]
Looks like you didn’t get it. It’s implemented already, you should test…

**Comment by Hasan-Shaker** [comment]
@xperseguers Its OK for me #10

**Comment by xperseguers** [comment]
Next time please do not close the ticket until it's actually merged onto the main branch.
